# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa7316cc3331da57a62cab4ed023019f99cf53773b0bac4aae3a58f41e042f4f94f138cd62cbd378e4ed703409e28fa301e791dff4e936fcefb6f5633031d522

test:
  secret_key_base: 29872c9ff0589773bc07b3bf5b2faebc09034dcfedb13c8aea89cc78bb535b1cd4fb7ca69ec9a507c968dd909fd4ba0deb62904714be8818397dde6e57ae452d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
